function frame = OctaZAligned(theta)

frame = [-sqrt(5/12)*sin(4 * theta), ...
    zeros(length(theta), 3), ...
    sqrt(7/12) * ones(length(theta), 1), ...
    zeros(length(theta), 3), ...
    sqrt(5/12)*cos(4 * theta)]';

end