function Y = RealY4Basis(realCoeffs, theta, phi)
dims = size(theta);
theta = theta(:);
phi = phi(:);

coeffs = diag([(3/16)*sqrt(35/pi), ...
              (3/4)*sqrt(35/(2*pi)), ...
              (3/16)*sqrt(5/pi), ...
              (3/8)*sqrt(5/(2*pi)), ...
              3/(128*sqrt(pi)), ...
              (3/8)*sqrt(5/(2*pi)), ...
              (3/16)*sqrt(5/pi), ...
              (3/4)*sqrt(35/(2*pi)), ...
              (3/16)*sqrt(35/pi)]);

phi_part = [sin(kron([4 3 2 1], phi)), ones(size(phi)), cos(kron([1 2 3 4], phi))];
theta_part = (sin(theta).^[4 3 2 1 0 1 2 3 4]) .* ...
    [ones(size(theta)), cos(theta), (5 + 7 * cos(2 * theta)), (1 + 7 * cos(2 * theta)) .* cos(theta), ...
    9 + 20 * cos(2 * theta) + 35 * cos(4 * theta), ...
    (1 + 7 * cos(2 * theta)) .* cos(theta), (5 + 7 * cos(2 * theta)), cos(theta), ones(size(theta))];
                          
Y = reshape((phi_part .* theta_part) * (coeffs * realCoeffs), dims);
end

